config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :images
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validates :picture, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :images, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end 
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /images or /images.json
  def index
    @images = Image.paginate(page: params[:page], per_page: 5)
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    File.delete('public/' + @image.picture.url) if @image.picture.url
    @image.destroy!
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:title, :picture, :description)
    end

    def require_same_user
      if current_user != @image.user
        flash[:alert] = "You can only edit or delete your own images."
        redirect_to @image
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to images_path if logged_in?
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Log in successful"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Log out successful'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome! You have successfully signed up'
      redirect_to images_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @images = @user.images.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = 'You account and all associated images have been deleted'
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = 'You can only edit your own account'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/images/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: image %>
      <%= form_with(model: image, class:'shawdow p-3 mb-5 bg-white rounded') do |form| %>

        <div class="form-group row">
          <%= form.label :title, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
              <%= form.text_field :title, class: 'form-control', placeholder:'Enter image title' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :picture, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class:'form-control-file' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :description, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
              <%= form.text_area :description, rows: 10, class: 'form-control', placeholder:'Enter image description' %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: 'btn btn-primary btn-lg'%>
        </div>
      <% end %>
      <%= link_to 'Cancel and return to images', images_path%>
    </div>
  </div>
</div>

app/views/images/_images.html.erb
<div class="container text-center">
  <% @images.each do |image| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card mb-3 shadow mb-5 bg-white rounded">
        <% if image.picture? %>
          <%= image_tag image.picture.url, class: 'card-img-top'%>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= image.title %></h5>
          <p class="card-text"><%= truncate(image.description, length: 15) %></p>
          <p class="card-text">
          <small class="text-muted">Created <%= time_ago_in_words(image.created_at) %> ago</small> |
          <small class="text-muted">Edited <%= time_ago_in_words(image.updated_at) %> ago </small><br>
          <small class="text-muted font-italic">by <%= link_to image.user.username, user_path(image.user) %></small></p>
          <div class="text-white">
            <%= link_to 'View', image, class: "btn btn-outline-primary" %>
            <% if logged_in? && image.user == current_user %>
              <%= link_to 'Edit', edit_image_path(image), class: "btn btn-outline-success" %>
              <%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/images/edit.html.erb
<h1 class="text-center mt-4">Edit image</h1>

<%= render 'form', image: @image %>

app/views/images/index.html.erb
<div class="flickr_pagination">
  <%= will_paginate @images, :container => false %>
</div>
<%= render 'images' %>
<br>
<div class="container">
  <div class="row">
    <div class="col-10 text-center">
      <%= link_to 'New Image', new_image_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/images/new.html.erb
<h1 class="text-center mt-4">Upload new image</h1>
<%= render 'form', image: @image %>

app/views/images/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-10 mt-4">
    <div class="card mb-3 shadow mb-5 bg-white rounded">
      <% if @image.picture? %>
        <%= image_tag @image.picture.url, class: 'card-img-top'%>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= @image.title %></h5>
        <p class="card-text"><%= @image.description%></p>
        <p class="card-text">
        <small class="text-muted">Created <%= time_ago_in_words(@image.created_at) %> ago</small> |
        <small class="text-muted">Edited <%= time_ago_in_words(@image.updated_at) %> ago </small><br>
        <small class="text-muted font-italic">by <%= link_to @image.user.username, user_path(@image.user) %></small></p>
        <div class="text-white">
          <% if logged_in? && @image.user == current_user %>
            <%= link_to 'Edit', edit_image_path(@image), class: "btn btn-outline-success" %>
            <%= link_to 'Delete', @image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <p>This application was created as a submission for the <a href="https://docs.google.com/document/d/1ZKRywXQLZWOqVOHC4JkF3LqdpO3Llpfk_CkZPR8bjak/edit#" class="text-white">Fall 2021 - Shopify Developer Intern Challenge</a></p>
    <small>Copyright &copy; Loewan Lafleur</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role='alert'>
    <%= msg %>

    <button type="button" class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Shopify Intern Challenge', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Users", users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Images
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'View all images', images_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <% if logged_in? %>
            <%= link_to 'Upload new image', new_image_path, class: 'dropdown-item' %>
          <% else %>
            <%= link_to 'Sign up to upload a new image', signup_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View your profile', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Edit your profile', edit_user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Delete your profile', user_path(current_user), class: 'dropdown-item text-danger', method: :delete, data: { confirm: 'Are you sure? This cannot be undone'} %>
          </div>
        </li>
      <% end %>


    </ul>
    <% if logged_in? %>
      <li class="btn btn-primary">
        <%= link_to 'Log out', logout_path, class: 'nav-link', method: :delete %>
      </li>
    <% else %>
      <li class="btn btn-primary">
        <%= link_to 'Log in', login_path, class: 'nav-link' %>
      </li>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyInternChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = 'd-flex flex-column'>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div id='page-content'>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-black">
    <h1 class="display-4">Image Repository</h1>

    <%= link_to 'Signup', signup_path, class: 'btn btn-primary text-white' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role='alert'>
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %> from being saved:</h4>
    <ul>
      <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class:'shawdow p-3 mb-5 bg-white rounded') do |form| %>

        <div class="form-group row">
          <%= form.label :username, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
              <%= form.text_field :username, class: 'form-control', placeholder:'Enter username' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :email, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.text_field :email, class:'form-control', placeholder:'Enter email' %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :password, class: 'col-2 col-form-label' %>
          <div class="col-sm-10">
              <%= form.password_field :password, class: 'form-control', placeholder:'Enter password' %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: 'btn btn-primary btn-lg'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 text-center">
      <h1>Edit your information</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>

  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card mb-3 shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <p class="card-text">
          <small class="text-muted">Joined <%= time_ago_in_words(user.created_at) %> ago</small> |
          <small class="text-muted font-italic">by <%= link_to user.username, user_path(user) %></small></p>
          <div class="text-white">
            <%= link_to 'View all images', user, class: "btn btn-outline-primary" %>
            <% if logged_in? && user == current_user %>
              <%= link_to 'Edit', edit_user_path(user), class: "btn btn-outline-success" %>
              <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 text-center">
      <h1>Sign Up!</h1>
    </div>
  </div>
</div>
<%= render 'form' %>
<div class="container">
  <div class="row">
    <div class="col-10 text-center">
      <h2>Already a user? Log in instead.</h2>
      <%= link_to 'Log In', login_path, class: 'btn btn-primary text-white' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-10 text-center">
      <h1><%= @user.username %></h1>
    </div>
  </div>
</div>

<% if logged_in? && @user == current_user %>
<div class="container mt-4">
  <div class="row">
    <div class="col-10 text-center">
      <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-success text-white" %>
    </div>
  </div>
</div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @images, :container => false %>
</div>

<%= render 'images/images' %>

<div class="container mt-4">
  <div class="row">
    <div class="col-10 text-center">
      <%= link_to 'Return to all users', users_path %>
    </div>
  </div>
</div>